model:
  noise_dim: 100
  generator:
    hidden_dims: [1200, 1200]
    output_dim: 784
  discriminator:
    hidden_dims: [240, 240]
    
training:
  num_epochs: 100
  batch_size: 128
  learning_rate: 0.0002
  beta1: 0.5
  k_steps: 1
  validate_every: 5
  compute_parzen: false
  parzen_sigma: 0.1